import Image from "next/image"
import { Footer } from "./Footer"
import { Header } from "./Header"
import { urlForImage } from "../lib/sanity"

export const Home = () => {
 return(
  <>
   <main>
    <Header/>
    <div className='font-body mb-4 px-10 text-base'>
        <div className='max-w-4xl mx-auto'>
       
        <h1 className="font-bold text-3xl mb-4">Hello there.</h1>
        <p>I’m <span className="font-bold">ohis</span> I am a software engineer. I love building polished web user interfaces with frontend technology.I am interested in user experience, accessibility and design system</p>

<p>As well as coding and designing, you can find me binging tv shows, eating and occasionally rambling on Twitter.</p>

<p className="p-3 my-3 rounded bg-gray-100 text-slate-800 shadow-sm shadow-slate-100 w-fit md:w-auto">Open to opportunities from mid-April 2023.</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum molestie purus venenatis, faucibus metus et, accumsan ex. Nunc rutrum, tortor sed placerat elementum, neque magna luctus quam, a bibendum mauris magna et augue. Suspendisse eros tortor, finibus eget faucibus a, sollicitudin at neque. Nam consectetur risus eget erat accumsan, sed venenatis arcu finibus. Ut eu facilisis ex, id tristique ipsum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Donec suscipit lacus quis lectus tincidunt consequat.

Mauris pharetra tincidunt metus, eget tincidunt odio rhoncus nec. Sed dignissim diam ut ante lobortis, eu iaculis lectus faucibus. Maecenas suscipit nunc ipsum, eu viverra dui mollis sit amet. Praesent et enim at tortor hendrerit venenatis. Proin fermentum ligula sit amet nulla pulvinar blandit. Donec facilisis tristique nisl, vitae lobortis lacus pretium eget. In mattis orci vitae auctor convallis. Maecenas nec sapien arcu. Fusce pharetra, justo ut lobortis cursus, velit ipsum semper ipsum, in condimentum elit odio id leo. Pellentesque a dapibus tellus.

Duis tempor tellus quis dolor dapibus pellentesque. Duis malesuada euismod leo, ac scelerisque nunc tincidunt nec. Curabitur sagittis nec purus id aliquet. Integer nisi arcu, finibus sed enim in, lobortis fermentum tortor. Nam vehicula enim eget nunc convallis, vitae dignissim leo accumsan. Donec non tortor mauris. Morbi lectus purus, tristique eu semper et, lacinia sed lectus. Duis enim tellus, gravida et ornare sit amet, dignissim in orci. Curabitur vitae tortor nec nisl interdum condimentum. Ut bibendum vehicula diam, ut malesuada turpis tristique a. Suspendisse in interdum justo, id maximus lacus. Ut commodo, nibh vitae aliquam commodo, augue orci hendrerit velit, ut consequat sem urna vitae ante.

Pellentesque id nisi neque. Nam ac sapien magna. Praesent varius sagittis nunc, at sollicitudin eros. Duis faucibus ultrices lacinia. Integer rhoncus, arcu tincidunt maximus laoreet, odio libero sollicitudin dui, sit amet porta urna elit in metus. Suspendisse ipsum massa, mattis a vestibulum sed, ornare a mauris. Donec eu enim ac lacus ultrices cursus. Mauris rhoncus felis vitae sem facilisis egestas.

Integer gravida rutrum rutrum. Maecenas aliquam dignissim justo quis varius. Praesent cursus libero vitae volutpat ultricies. Aenean tellus enim, facilisis a metus ut, vehicula varius sem. Proin rutrum volutpat mauris a sollicitudin. Aliquam ligula libero, mattis feugiat est at, laoreet elementum ligula. Cras eu vulputate leo, ut malesuada felis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In sollicitudin consequat diam eget ornare.

Vivamus fringilla odio eget risus ultrices, vestibulum mattis ligula consectetur. Nulla eu porttitor est. Suspendisse est elit, sodales porttitor ultrices id, varius auctor velit. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus ac mauris libero. Vestibulum a maximus nisi, vitae placerat ante. Proin dignissim, augue pretium pretium tincidunt, tortor urna viverra justo, nec lobortis urna lacus non orci. Curabitur mollis pellentesque leo, nec finibus dolor finibus ac. Morbi diam mi, luctus mollis euismod vitae, vulputate non velit. Nunc rutrum varius enim non sodales.

Suspendisse euismod efficitur ipsum, vitae convallis ipsum vulputate finibus. Sed mollis cursus ante, ut imperdiet purus dapibus eget. Nam ullamcorper, enim fermentum mollis porta, metus arcu porttitor dui, eget molestie purus est sed elit. Proin elementum maximus ipsum eget rutrum. Curabitur ultrices aliquam ipsum, ut fermentum risus fermentum non. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Morbi id ligula risus. Fusce ac facilisis magna. Morbi ornare scelerisque orci in iaculis. Morbi ac urna in sem lacinia vestibulum placerat ac quam. Donec vitae est nec nisl bibendum varius. Ut enim sem, ultricies euismod tortor vel, imperdiet pharetra lorem. Proin porttitor, enim vitae fermentum placerat, quam libero congue orci, sed pulvinar nisl neque eu velit.

Praesent lobortis turpis at odio bibendum lacinia. Suspendisse rhoncus sollicitudin magna, at varius elit consequat vel. Nullam convallis elit non dolor auctor placerat ac in risus. Maecenas nulla sem, accumsan et semper id, eleifend sed risus. Curabitur dictum maximus nisl, eget tristique justo dignissim in. Donec commodo, mauris in aliquet tristique, quam metus faucibus purus, a molestie sem diam at erat. Nullam ut ipsum molestie, aliquam mauris nec, porta lacus. Ut molestie imperdiet lorem, id aliquet nibh ullamcorper quis.

Nam ac rutrum ante, eu rhoncus quam. Integer finibus erat sed libero congue pellentesque. Suspendisse lacus massa, cursus ac aliquam vel, tempor eu lorem. Integer at mi ac sapien fringilla dignissim. Aliquam tincidunt quis leo rhoncus rhoncus. Vestibulum feugiat erat sit amet justo auctor, sit amet sodales risus rhoncus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed consequat blandit ligula nec ornare. Ut eleifend eleifend rutrum. Mauris sed massa sit amet arcu aliquam ornare. Sed vel ultricies libero. Quisque vel euismod mi.

Pellentesque in arcu vitae lacus scelerisque venenatis. Mauris accumsan non turpis ac euismod. Aenean tempus libero in faucibus facilisis. Mauris in placerat enim. Vestibulum turpis augue, aliquam vitae porta consequat, commodo finibus odio. Proin nec pharetra risus. Pellentesque maximus nibh velit, a bibendum magna sodales eu. Vestibulum dolor augue, elementum et accumsan ut, tristique in risus. Curabitur eget venenatis purus, ac convallis nibh. Quisque nec nisl sodales, volutpat nibh et, pharetra leo. Donec vestibulum, tellus vitae finibus convallis, ipsum risus facilisis mi, ut malesuada dolor dui vitae odio. Sed consequat erat id ex vestibulum, nec efficitur urna semper. Donec nec mollis neque.

In nec erat felis. Proin fringilla orci eu urna laoreet pretium ut sed sem. Donec quis neque tristique, venenatis nisi sed, ultricies nibh. Interdum et malesuada fames ac ante ipsum primis in faucibus. Quisque at magna non augue fringilla dictum. Maecenas porttitor condimentum mauris, consequat vestibulum nunc placerat eu. Morbi euismod quam turpis, eget tempor sapien congue viverra. Cras facilisis tellus et tortor lacinia iaculis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Duis aliquam, tellus in scelerisque lobortis, tortor ante aliquet libero, id aliquet elit sapien et metus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum mattis est vel lacus venenatis, nec maximus lacus sollicitudin. Phasellus ultrices dolor leo, eget pulvinar arcu malesuada eu. Suspendisse ullamcorper laoreet nunc, sit amet luctus dolor feugiat eget. Suspendisse pellentesque leo risus. Pellentesque vel finibus tortor.

Vestibulum posuere id nisi ac sagittis. Sed sit amet suscipit libero, et porttitor arcu. Nam tincidunt commodo ex, a posuere orci tincidunt a. Vivamus eu orci tellus. Vestibulum varius purus non turpis maximus malesuada. Proin ultricies, erat et rutrum maximus, massa ex rhoncus nisi, eu lobortis nunc purus sit amet orci. Vivamus nec nisl sed ipsum pellentesque vestibulum. Nunc aliquam ultrices justo eget egestas. Vivamus condimentum sapien massa, ornare pulvinar libero feugiat in. Praesent erat sapien, vulputate sit amet tempor sed, porta pretium urna. Curabitur nec fringilla neque. Nulla tellus nisi, tincidunt vel congue sed, pellentesque sit amet neque. Pellentesque auctor risus et ligula convallis, sit amet accumsan tellus luctus.

Sed vitae purus sit amet neque faucibus maximus. Aliquam erat volutpat. Aliquam aliquam est eget leo sollicitudin, fringilla sagittis quam condimentum. Quisque tempus arcu semper ipsum bibendum, at placerat sem tincidunt. Pellentesque tincidunt feugiat lectus. Vivamus semper, justo sit amet euismod mollis, turpis arcu consectetur dolor, eget tempor tellus nulla quis velit. Etiam pretium, leo ac sollicitudin venenatis, eros enim sollicitudin orci, at gravida tellus risus vel turpis. Nullam vel fringilla arcu, vitae elementum leo. Duis ut rhoncus justo, quis auctor est. Cras consectetur tellus justo, ultricies aliquam erat egestas ac. Aenean vel eros iaculis, tempor nibh vel, dignissim odio. Morbi eu ex facilisis, scelerisque metus nec, rhoncus tortor. Vestibulum vitae egestas nibh, sit amet aliquet tortor. Nam vestibulum dolor ac feugiat maximus. Nunc bibendum justo enim, eget auctor enim placerat ac. Integer ac dapibus mi, sed consequat nulla.

Etiam convallis nibh ligula, eget consectetur nisl lobortis pharetra. Proin sit amet sodales neque, eget aliquet justo. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nam volutpat consectetur orci ac semper. Nunc tristique lacinia hendrerit. Ut eu tristique eros. In sed ipsum eget lacus egestas commodo sit amet a diam. Vestibulum vestibulum orci et erat imperdiet, quis finibus tellus pellentesque. Praesent consequat nisi a porttitor consequat.

Sed dolor nibh, blandit ut urna eu, luctus hendrerit nisi. In malesuada venenatis tortor, non pulvinar felis. Praesent pretium ut ex laoreet congue. Nulla vel auctor dui, et auctor sem. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed condimentum est id urna laoreet mattis. Mauris auctor nibh in tincidunt vulputate. Nullam commodo mi non ultrices sollicitudin. Sed scelerisque vulputate nisl, in egestas tellus consectetur ac. Sed nec neque sit amet urna ultrices luctus. Duis placerat mauris vitae turpis maximus venenatis. Cras rutrum dictum est non porta.

Vestibulum eget nisl lacus. Ut porta, nibh id interdum interdum, nulla urna laoreet lacus, at dignissim neque erat quis urna. Integer consectetur condimentum augue, ac venenatis enim rutrum sit amet. Aenean quis risus a lacus pellentesque gravida. Pellentesque in porta arcu, vitae condimentum urna. Fusce pharetra mauris mauris, in luctus nunc interdum ut. Ut pretium dignissim sapien ut ullamcorper. Nam tempus egestas lacus ac efficitur. Phasellus convallis dapibus enim, eget fermentum sapien varius vel. Morbi a vulputate ex.

Nam in vehicula mi. Pellentesque eget ipsum eget justo mollis rutrum eu id sapien. Quisque suscipit mi vel nunc commodo fermentum. Proin non porttitor nisl. Duis a lorem nec quam imperdiet sodales non in sem. Cras cursus eleifend turpis, non maximus augue cursus ac. Aliquam diam dolor, consectetur luctus odio vitae, facilisis tempus sem. In tincidunt rutrum urna vitae scelerisque. Maecenas sed orci erat. Pellentesque blandit auctor ante, non mattis quam aliquet a. Nunc finibus dui et libero elementum, vel posuere elit sagittis. Etiam justo risus, pulvinar vitae aliquet sit amet, dignissim eget arcu. Mauris sit amet commodo quam. Aliquam at consectetur elit, nec efficitur enim.

Cras id eros aliquam, tincidunt turpis faucibus, rhoncus tellus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed tristique dignissim dui euismod tempus. Cras cursus tincidunt tristique. Quisque molestie lacinia dolor, euismod mollis sem tincidunt in. Pellentesque aliquet sem nec neque consectetur, ac faucibus felis laoreet. Cras vestibulum odio turpis, at blandit metus finibus vel. Morbi quis lacus id metus semper bibendum. Nulla at mollis lacus. Duis ac interdum turpis.

Ut nec euismod orci. Nam consequat justo ante, nec condimentum quam commodo a. Nunc eu vulputate lectus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Curabitur vel enim lacus. Mauris dignissim consectetur arcu in dictum. Nunc iaculis diam vel risus rhoncus, bibendum gravida arcu lobortis. Suspendisse a augue ipsum. Maecenas a nisi nisl. In ornare, augue dignissim scelerisque hendrerit, augue diam pulvinar urna, a laoreet sem lorem a leo. Vivamus pretium lacinia purus nec convallis. Nulla dictum vitae enim vitae imperdiet. Donec ac ultricies dui, sed fermentum lorem. Curabitur vel dapibus lectus. Integer quam sapien, malesuada non nulla ac, commodo ullamcorper orci.

Vestibulum eu tristique nibh. Nam quis rhoncus sem, vel pellentesque risus. Maecenas nibh eros, laoreet a mauris sed, facilisis laoreet orci. Nullam efficitur rhoncus mauris in pellentesque. Nunc egestas eleifend semper. Sed posuere id urna nec luctus. Nam varius turpis sed eros porta, sed ornare nulla accumsan.

Sed ultrices enim eu diam euismod, posuere bibendum leo consectetur. Sed vehicula ex dignissim laoreet aliquam. Nullam eu vulputate velit. Vestibulum sed vulputate nulla, vitae egestas lorem. Ut sed lectus justo. Praesent finibus ultricies ipsum vel mollis. Morbi tristique, metus quis efficitur suscipit, ex purus posuere ligula, vel commodo lacus leo ac justo. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Quisque tempor, metus eu convallis sollicitudin, urna ligula rutrum sem, vel tempor metus lorem et nunc. Maecenas et felis rhoncus, mattis orci eu, rutrum arcu. Aenean libero felis, pellentesque mollis interdum sed, rutrum vel mauris. Donec at varius neque. Donec pharetra purus nec nisi consequat, sed consectetur massa eleifend.

Integer aliquam massa in ipsum pretium porttitor. Sed nisi metus, blandit malesuada justo fringilla, suscipit fermentum tortor. Nullam et erat sed ipsum aliquet faucibus. Praesent eget fringilla erat. Praesent vel velit quis est convallis feugiat tincidunt sit amet magna. Vivamus vitae pulvinar turpis. Donec et accumsan metus. Ut egestas nec justo congue gravida. Proin feugiat finibus neque ut suscipit. Nam ullamcorper fringilla erat, non pellentesque justo. Ut suscipit porta diam, sit amet sollicitudin eros ultricies vitae. Mauris feugiat nisi id sapien pretium, ut accumsan nulla viverra. Nulla dapibus id quam id faucibus. Phasellus bibendum in neque non rutrum. Sed at lectus condimentum libero semper interdum.

Nam eget lectus risus. Pellentesque leo ipsum, facilisis ac quam eget, suscipit blandit ligula. Nam nisl neque, sagittis a ex vel, vulputate rutrum nunc. Sed at convallis nunc, sit amet laoreet metus. Vestibulum condimentum, nunc ut placerat interdum, mauris tortor pretium nibh, a aliquam eros enim ac augue. In tortor nisl, facilisis at maximus sed, sodales eu dolor. Nam mauris libero, dapibus id nisi ac, accumsan tristique dui. Morbi finibus justo sed eros suscipit blandit. Curabitur convallis semper ligula, sed malesuada diam scelerisque sed. Etiam malesuada nisl eros, quis lobortis turpis pellentesque ac. Nunc porta volutpat dapibus.

Aliquam in turpis mattis, commodo lorem vel, dictum orci. Vivamus in ante at nulla malesuada tincidunt. Pellentesque dui velit, finibus eget libero sit amet, consequat elementum sapien. Maecenas ac congue ipsum, ut sodales leo. Maecenas volutpat, enim sed aliquet ultrices, diam tellus ornare urna, euismod venenatis metus enim in diam. In sagittis faucibus ligula ac suscipit. Sed sapien elit, porttitor vitae quam sit amet, euismod congue eros. Nunc vitae rhoncus purus, non tempor nisl. Donec lacinia imperdiet arcu eu dictum. Donec bibendum, augue vel viverra euismod, ligula sem facilisis dolor, sit amet lobortis mi dolor id lorem. Etiam dapibus erat sit amet justo hendrerit, nec euismod augue semper. Sed in porttitor nibh. Pellentesque ac sodales risus. Curabitur ullamcorper ipsum a lacinia consequat. Donec cursus purus et nisi consequat pulvinar.

Fusce nec euismod nunc. Nunc euismod orci non metus feugiat malesuada. Phasellus laoreet ligula in mi consequat, pretium eleifend justo condimentum. Nullam nunc sem, lacinia et libero gravida, lacinia accumsan ex. Nulla eget sem lorem. Aliquam aliquet tincidunt gravida. Duis sapien turpis, luctus eu rhoncus id, lacinia quis felis. Donec feugiat urna eget aliquet hendrerit. Cras malesuada scelerisque magna, in consectetur orci imperdiet sit amet. Curabitur leo neque, bibendum nec leo congue, fringilla placerat enim. Mauris lacinia velit egestas, vulputate metus ut, ultricies erat.

Etiam molestie est ac orci maximus egestas. Praesent tempus nulla sed velit consectetur vehicula. Nullam vitae dolor sit amet lorem commodo condimentum at eu purus. Ut ut dignissim nisl. Curabitur vel nisi aliquam, ultrices odio non, iaculis neque. Vivamus viverra vulputate facilisis. Pellentesque tristique laoreet mauris, in accumsan nulla laoreet non. Duis posuere lectus orci, vitae vehicula urna vulputate maximus. Pellentesque rhoncus id lorem ac viverra. Suspendisse vestibulum eget mi sit amet fermentum. Curabitur imperdiet convallis blandit. Pellentesque convallis malesuada ante. Cras ut tellus in eros pulvinar sollicitudin.

Aliquam sed cursus tellus. Aliquam finibus, dolor nec dapibus pretium, magna nunc aliquet tortor, vel lobortis arcu ipsum sed orci. Nulla ultrices consectetur ligula. Nam vel fermentum enim. Donec tempus, massa vehicula blandit laoreet, nibh elit porttitor erat, feugiat molestie metus augue vitae ligula. Phasellus ultricies ac odio porta dictum. Aliquam quis laoreet leo. Curabitur faucibus imperdiet ante. Maecenas semper purus purus, sit amet porta ante ullamcorper vitae. Maecenas in pharetra dolor, pharetra maximus odio. Quisque bibendum pretium varius. Phasellus tempor erat sit amet ligula ultricies, eu venenatis turpis ultricies. Quisque venenatis, arcu a rutrum auctor, quam ipsum tempus tortor, vestibulum sodales dui neque a lorem.

Suspendisse sit amet sodales turpis. Nullam bibendum quam a felis consectetur sollicitudin quis sed mi. Suspendisse potenti. Praesent risus purus, tempor sodales tincidunt ut, condimentum ac ligula. Aenean non tellus ut odio porttitor vulputate nec ac nibh. Vivamus aliquet tristique felis, eget ornare velit aliquet id. Etiam nibh elit, hendrerit eget nunc at, tincidunt lobortis dui. Pellentesque eu justo iaculis, consectetur dolor et, fringilla ante. Donec blandit eros eu orci dapibus, vel molestie mauris euismod. Suspendisse potenti. Morbi pretium lectus a mauris aliquet, non iaculis dui dapibus. Curabitur sagittis metus massa, cursus tincidunt ex egestas viverra. Morbi dapibus, nisl gravida elementum euismod, quam velit ultrices augue, a lobortis ipsum elit in nisl. Quisque nec tincidunt ante, eget porta lectus.

Phasellus pharetra magna eu purus consectetur elementum. Morbi quis dapibus velit. Fusce consequat auctor tristique. In hac habitasse platea dictumst. Morbi non erat ligula. Aenean mattis magna in neque volutpat, vel congue augue aliquam. Quisque ac libero hendrerit, consequat libero ac, auctor sem. Ut molestie mi id risus lobortis vulputate. Phasellus facilisis tristique ante porttitor dignissim. Sed eget congue tellus. Vivamus pharetra sem quis convallis efficitur. Ut mattis eleifend velit, sit amet dignissim lacus maximus non. Nullam nec velit risus. Fusce vitae rutrum eros. Nulla tempus fringilla nunc, at suscipit diam varius vitae.

Maecenas efficitur aliquet mi, at sollicitudin urna facilisis sit amet. Suspendisse non diam nunc. Nullam porta odio leo, eget gravida lorem consequat vel. Etiam eu lorem tempor lectus interdum aliquet sit amet quis nibh. Nulla non magna in quam consequat rhoncus. Sed id bibendum erat. In vel dapibus dui, ut auctor nisl. Nunc rhoncus lorem id arcu fermentum, id eleifend elit dignissim. Aliquam lorem augue, viverra eget vulputate sagittis, suscipit vitae lacus. Suspendisse at sodales lacus. Cras eu purus vitae lectus sagittis vestibulum eget viverra tellus.</p>
        </div>
        </div>
    <Footer/>
   </main>
  </>
 )
}